codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: 90%
        threshold: 0%
